#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pushbotx[-1]
	add ucitrack pushbotx
	set ucitrack.@pushbotx[-1].init=pushbotx
	commit ucitrack
EOF

# 确保脚本可执行
chmod +x /usr/bin/pushbotx/pushbotx 2>/dev/null

# 创建临时目录
mkdir -p /tmp/pushbotx

# 注册开机自启
/etc/init.d/pushbotx enable 2>/dev/null

rm -rf /tmp/luci-*
exit 0