#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	state=`pgrep -f "/usr/bin/pushx/pushx"`
	if [ ! -z "$state" ]; then
		restart
	else
		/usr/bin/pushx/pushx &
	fi
	echo "pushx is starting now ..."
}

stop() {
	kill -9 `pgrep -f "/usr/bin/pushx/pushx"` 2>/dev/null
	echo "pushx exit ..."
}

restart(){
	stop
	sleep 1
	start
	echo "restarted."
}