#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	state=`pgrep -f "/usr/bin/pushbotx/pushbotx"`
	if [ ! -z "$state" ]; then
		restart
	else
		/usr/bin/pushbotx/pushbotx &
	fi
	echo "pushbotx is starting now ..."
}

stop() {
	kill -9 `pgrep -f "/usr/bin/pushbotx/pushbotx"` 2>/dev/null
	echo "pushbotx exit ..."
}

restart(){
	stop
	sleep 1
	start
	echo "restarted."
}
